format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipTcp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_TCP_COMMANDS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_TCP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTcp, value: '48456'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: tcpipTcp}
