format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipTelnet}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_TELNET_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTelnet, value: '56'}
- type: ElementPosition
  attributes: {x: '26', y: '374', id: tcpipTelnet}
