format_version: v1.0
type: GroupComponent
attributes: {displayName: BASIC CONFIGURATION, id: BASIC CONFIGURATION}
children:
- type: ElementPosition
  attributes: {x: '216', y: '133', id: BASIC CONFIGURATION}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: DRIVER LAYER, namespace: tcpipNetConfig_0, id: NETCONFIG_MAC_Dependency,
      targetAttachmentID: 'drvEmac0:libdrvMac0'}
  - type: Attachment
    attributes: {namespace: tcpipStack, id: Core_SysConsole_Dependency}
