format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipTftpc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_TFTPC_DEFAULT_IF}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTftpc, value: EMAC0}
  - type: Integer
    attributes: {id: TCPIP_TFTPC_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTftpc, value: '560'}
- type: ElementPosition
  attributes: {x: '203', y: '380', id: tcpipTftpc}
