format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIperf}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_IPERF_MAX_INSTANCES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_RX_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16384'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TIMING_ERROR_MARGIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TX_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16384'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TX_BW_LIMIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '100'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TX_QUEUE_LIMIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
- type: ElementPosition
  attributes: {x: '415', y: '53', id: tcpipIperf}
