format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDnss}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_DNSS_CACHE_PER_IPV6_ADDRESS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_DNSS_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDnss, value: '424'}
- type: ElementPosition
  attributes: {x: '530', y: '300', id: tcpipDnss}
