format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipStack}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_STACK_CALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: calloc}
  - type: Integer
    attributes: {id: TCPIP_STACK_DRAM_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '124287'}
  - type: Integer
    attributes: {id: TCPIP_STACK_HEAP_SIZE_RECOMMEND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '34'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: tcpipStack}
