format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipZeroConf}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_USE_MULTI_CAST_DNS_ZERO_CONFIG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_ZC_MDNS_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipZeroConf, value: '32'}
- type: ElementPosition
  attributes: {x: '870', y: '140', id: tcpipZeroConf}
