format_version: v1.0
type: UniqueComponent
attributes: {id: tcpip_transport_config}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_TCP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_UDP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '19', y: '22', id: tcpip_transport_config}
