format_version: v1.0
type: UniqueComponent
attributes: {id: drvEmac0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_MAC_PHY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvEmac0, value: KSZ8081}
  - type: Integer
    attributes: {id: MAX_RX_PACKET_POINTERS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvEmac0, value: '1024'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: MAC_PHY_Dependency0}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvExtPhyKsz8081}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: libdrvExtPhyKsz8081}
- type: ElementPosition
  attributes: {x: '540', y: '20', id: drvEmac0}
