format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyKsz8081}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_ETHPHY_RESET_CALLBACK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_ETHPHY_USE_RESET_CALLBACK}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_INTMAC_PHY_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: TCPIP_INTMAC_PHY_CONFIG_RMII}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvExtPhyKsz8081, value: 'true'}
- type: ElementPosition
  attributes: {x: '420', y: '19', id: drvExtPhyKsz8081}
