format_version: v1.0
type: UniqueComponent
attributes: {id: dbgu}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '108'}
  - type: Integer
    attributes: {id: DBGU_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '200000000'}
  - type: File
    attributes: {id: DBGU_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/dbgu_6059/templates/plib_dbgu_ring_buffer.h.ftl}
  - type: Boolean
    attributes: {id: DBGU_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: 'true'}
  - type: KeyValueSet
    attributes: {id: DBGU_OPERATING_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '2'}
  - type: Boolean
    attributes: {id: DBGU_RING_BUFFER_ENABLE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: 'true'}
  - type: Boolean
    attributes: {id: DBGU_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: 'true'}
  - type: Comment
    attributes: {id: DBGU_RING_BUFFER_SIZE_CONFIG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: DBGU_RX_RING_BUFFER_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '512'}
  - type: File
    attributes: {id: DBGU_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/dbgu_6059/templates/plib_dbgu_ring_buffer.c.ftl}
  - type: Integer
    attributes: {id: DBGU_TX_RING_BUFFER_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2560'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: 'true'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: DBGU_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_console_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_console_UART_dependency}
- type: ElementPosition
  attributes: {x: '44', y: '270', id: dbgu}
